### ISSUE TITLE
User is undefined in req.session

### ISSUE THREAD

**Issue by Razaik25** [Razaik25/shopMate#7]
I have my user authentication working, but my user authorization is not working.
This it output of the req.session object after a user logs in:

Session {
  cookie: 
   { path: '/',
     _expires: Mon Mar 28 2016 16:41:53 GMT-0400 (EDT),
     originalMaxAge: 2592000000,
     httpOnly: true },
  user: undefined }

I have required
 var session = require('express-session'); in db/pg_users.js 

I have requiresd
var session = require('express-session');
var pgSession = require('connect-pg-simple')(session); in server.js

Create user function:
function createUser(req, res, next) {
  createSecure(req.body.name,req.body.email, req.body.password, saveUser);
  function saveUser(name,email, hash) {
    pg.connect(connectionString, function(err, client, done) {
      if (err) {
        done();
        console.log(err);
        return res.status(500).json({success: false, data: err});
      }

```
  var query = client.query("INSERT INTO users( name,email, password_digest) VALUES ($1, $2, $3);", [name, email, hash], function(err, result) {
    done();
    if (err) {
      return console.error('error running query', err);
    }

    // res.users = result.rows;
    next();
  });
});
```

  }
}

**Comment by cuivienor** [comment]
Hey Raz, sorry for not responding sooner. Did you resolve this?

**Comment by Razaik25** [comment]
Hey Peter, the issue is resolved now. I had problem with variable naming and added  
saveUninitialized: true in app.use(session).
Thanks for getting back.
